# $schema=./.air.toml.json
# Air configuration file for live reloading

root = "."
tmp_dir = "tmp" # Directory for temporary files

[build]
  args_bin = []
  bin = "./tmp/app"
  cmd = "go build -o ./tmp/app ./cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = "./tmp/app"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
