FROM golang:1.24.3-alpine

WORKDIR /app

# Install Air for live reloading and other necessary tools
RUN apk update && \
  apk add --no-cache git curl tzdata && \
  go install github.com/air-verse/air@v1.61.1

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 8080

# Run Air for live reloading
CMD ["air", "-c", ".air.toml"]
