version: "3.8"

services:
  app:
    build: .
    container_name: consistency-api
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - LOG_LEVEL=debug
      - LOG_PRETTY=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=consistency_service
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_SSL_MODE=disable
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./docs:/app/docs:ro # Mount docs for swagger
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: consistency-db
    environment:
      - POSTGRES_DB=consistency_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
