service: consistency-service

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  memorySize: 128  # Minimum memory for cost optimization
  timeout: 30
  environment:
    ENV: production
    LOG_LEVEL: error
    DB_HOST: ${env:DB_HOST}
    DB_PORT: 5432
    DB_NAME: consistency_service
    DB_SSL_MODE: disable
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  api:
    handler: bootstrap
    events:
      - httpApi:
          path: /{proxy+}
          method: any
      - httpApi:
          path: /
          method: any

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.consistency-production.shubhams.dev
    certificateArn: arn:aws:acm:us-east-1:649024131095:certificate/2c8a7a6d-ae93-4dd1-8f5e-679864789461
    createRoute53Record: false  # Since you're using Squarespace DNS

package:
  individually: true
  patterns:
    - '!./**'
    - './bootstrap' 